export enum HeatLevel {
  QUALIFICATION = "QUALIFICATION",
  INTERMEDIATE = "INTERMEDIATE",
  SEMI_FINAL = "SEMI_FINAL",
  FINAL = "FINAL",
  HOPE_ROUND = "HOPE_ROUND",
  SHOW_ROUND = "SHOW_ROUND",
}
