export enum HeatState {
    INITIALIZED = 'INITIALIZED',
    STARTED = 'STARTED',
    ASSESSED = 'ASSESSED',
    CALCULATE = 'CALCULATE',
    REJECT = 'REJECT',
    EDIT = 'EDIT',
    SUBMIT = 'SUBMIT',
    CREATE_RANKING = 'CREATE_RANKING',
    SHOW_RESULT = 'SHOW_RESULT',
    FINISHED = 'FINISHED',

}
