export enum HeatState {
    INITIALIZED = 'INITIALIZED',
    STARTED = 'STARTED',
    JUDGE_ASSESSED = 'JUDGE_ASSESSED',
    OBSERVER_ASSESSED = 'OBSERVER_ASSESSED',
    TIME_MEASURED = 'TIME_MEASURED',
    CALCULATED = 'CALCULATED',
    RESULT_RELEASED = 'RESULT_RELEASED',
    FINISHED = 'FINISHED',
    ASSESSED = 'ASSESSED',
    OBSERVER_ASSESSING = 'OBSERVER_ASSESSING',
    TIME_MEASURING = 'TIME_MEASURING',
}
