export enum HeatState {
    INITIALIZED = 'INITIALIZED',
    STARTED = 'STARTED',
    ASSESSED = 'ASSESSED',
    CALCULATED = 'CALCULATED',
    RESULT_RELEASED = 'RESULT_RELEASED',
    FINISHED = 'FINISHED',
}
