export enum RoundState {
    INITIALIZED = 'INITIALIZED',
    CREATED = 'CREATED',
    DRAWN = 'DRAWN',
    STARTED = 'STARTED',
    EVALUATED = 'EVALUATED',
    TRANSFERRED = 'TRANSFERRED',
    FINISHED = 'FINISHED',
}
