export interface DrbvAcroData {
    readonly Nr: string,
    readonly Akrobatik: string,
    readonly Langtext: string,
    readonly Einstufung: string,
    readonly RR_A: string,
    readonly RR_B: string,
    readonly RR_C: string,
    readonly RR_J: string,
    readonly RR_S: string,
    readonly F_RR_M: string,
    readonly F_RR_J: string,
    readonly F_RR_LF: string,
    readonly F_RR_GF: string,
    readonly F_RR_ST: string,
    readonly Gruppen_ID_1: number,
    readonly Gruppen_ID_2: number,
    readonly Gruppen_ID_3: number,
    readonly Gruppen_ID_4: number,
    readonly Gruppen_ID_5: number,
    readonly Bemerkung: string,
}
