export interface StartDataAppointmentData {
    readonly Terminnummer: string,
    readonly Datum: string,
    readonly Clubname_kurz: string,
    readonly Mitgliedsnr: number,
    readonly Cup_Serie: string,
    readonly Bezeichnung: string,
    readonly Raum: string,
    readonly Strasse: string,
    readonly Ort: string,
    readonly PLZ: number,
    readonly Beginn: string,
    readonly Ende: string,
    readonly Wettbewerbsart: string,
    readonly Startklasse: string,
    readonly Turnierleiter: string,
    readonly Einschraenkungen: string,
    readonly Ansprechpartner: string,
    readonly Tel_Ansprechpartner: string,
    readonly Beginn_Abendveranstaltung: string,
}
