export interface StartDataRrData {
    readonly Buchnr: number,
    readonly Anrede1: string,
    readonly Vorname1: string,
    readonly Nachname1: string,
    readonly Anrede2: string,
    readonly Vorname2: string,
    readonly Nachname2: string,
    readonly Startklasse: string,
    readonly Clubnr: number,
    readonly Clubname_kurz: string,
    readonly LRRVERB: string,
    readonly RFID1: number,
    readonly RFID2: number,
}
